version: '3.8'

services:
  # NestJS Backend
  backend:
    build: ./backend
    container_name: nextjs_stack_backend
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - PORT=3001
    ports:
      - "3002:3001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
