[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.environment]
NODE_ENV = "production"

[build.buildCommand]
command = "cd backend && npm install && npm run build"
